on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Install Bril 
        run: cd; git clone https://github.com/sampsyo/bril.git

      - name: Install deno and flit 
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          echo 'export DENO_INSTALL="/home/runner/.deno"' >> ~/.bashrc
          echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          python3 -m pip install flit

      - name: Bril tools
        run: |
          cd ~/bril
          echo "DENO_INSTALL=/home/runner/.deno" >> $GITHUB_ENV
          echo "PATH=/home/runner/.deno/bin:$PATH" >> $GITHUB_ENV
          source ~/.bashrc
          /home/runner/.deno/bin/deno install --allow-env --allow-read ts2bril.ts
          /home/runner/.deno/bin/deno install brili.ts 
          cd bril-txt
          flit install --symlink --user

       

   
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
